### ISSUE TITLE
Error in Nuxt

### ISSUE THREAD

**Issue by adamkhan** [BKWLD/vue-balance-text#1]
Hi, thanks for making this. I can't get it working though. Using the Nuxt install method, I get an error in vue-balance-text/nuxt/plugin.js at line 7:

`Vue.directive('balance-text', directive);`

The error is: 

> TypeError: Vue.directive is not a function

I don't understand the environment well enough yet to suggest how to fix it.

**Comment by weotch** [comment]
Can you open up the package in your project's `node_modules` and do a `console.log(Vue)`?  I'm curious what is being resolved for the `vue` package, like why it wouldn't hvae a directive function...

- Directive docs: https://vuejs.org/v2/api/#Vue-directive

**Comment by adamkhan** [comment]
Thanks for responding. Trying but not sure what you're telling me to do. To take a look at balance-text's package.json file?

**Comment by adamkhan** [comment]
Hi @weotch, I'm revisiting this and still have the same problem. I didn't understand your instructions for debugging, can you repeat with some further detail?

I tried your similar vue-unorphan and the same problem happens at the same spot...

**Comment by adamkhan** [comment]
Hi again, revisiting this months later in Nuxt 2. There's no longer an error but Balance Text doesn't seem to be doing anything. Could you spare a bit of time to help me get it working?

**Comment by weotch** [comment]
It hasn't worked when applied to children of the node it's attached to, however I just added the `children` modifier that's documented here now:

https://github.com/BKWLD/vue-balance-text#usage

That might help you out.
