### ISSUE TITLE
<br> causes screen readers to pause mid-sentence

### ISSUE THREAD

**Issue by jonjahr** [BKWLD/vue-balance-text#5]
Just got a Foxhole ticket that says:
Notice that the "Bringing the spirit of California into everything we do." heading copy is read separately by the screen reader due to "br'.

An easy fix IMO would be to add `aria-hidden="true"` to the `br` element that's generated by vue-balance-text.

**Comment by jonjahr** [comment]
Oh... this package just wraps another dependency called `balance-text`.  Maybe not that simple.

**Comment by weotch** [comment]
Yeah, I like your suggestion, maybe we PR _that_ package.  Or make a fork of it, try out your suggested fix with it, once Foxhole approves, submit PR to it.

**Comment by jonjahr** [comment]
Alright, I PRed the main [balance-text package](https://github.com/adobe/balance-text/pull/148).  Meantime, I made a branch on this package that uses the fork.  I'll do a PR now.
